export const ecosystemProducts = [
  {
    id: "02",
    name: "Kradle",
    mark: "KRADLE™",
    category: "Maternal & Health Monitoring",
    purpose: "Maternal and healthcare monitoring",
    accent: "Health",
    href: "/product/kradle",
    image: null,
    features: [
      "Doppler fetal heartbeat detection",
      "Maternal heart rate monitoring",
      "Blood oxygen (SpO₂)",
      "Body temperature sensing",
      "Gestural emergency alerts",
      "AI health assistant & telemedicine",
    ],
    users: [
      "Pregnant women",
      "Midwives",
      "Doctors",
      "Rural healthcare workers",
      "Maternal health NGOs",
    ],
    value:
      "Reducing maternal and infant mortality through wearable monitoring and early intervention.",
  },
  {
    id: "01",
    name: "Kinetix",
    mark: "KINETIX™",
    category: "Sports & Athletic Performance",
    purpose: "Sports performance and training",
    accent: "Performance",
    href: "/product/kinetix",
    image: null,
    features: [
      "Motion tracking",
      "Biometric monitoring",
      "Grip-force sensing",
      "Muscle activity monitoring",
      'Coaching AI: "Edwin"',
      "Performance analytics & injury prediction",
    ],
    users: [
      "Boxers",
      "Cyclists",
      "Runners",
      "Golfers",
      "Tennis players",
      "Professional sports teams",
    ],
    value: "Turning every training session into measurable performance data.",
  },
  {
    id: "03",
    name: "Kursor",
    mark: "KURSOR™",
    category: "Human–Computer Interaction",
    purpose: "Human-computer interaction",
    accent: "Interaction",
    href: "/product/kursor",
    image: null,
    features: [
      "Air mouse functionality",
      "Gesture-based cursor control",
      "Virtual keyboard",
      "Presentation control",
      "AR/VR navigation",
      "Voice commands & haptic feedback",
    ],
    users: [
      "Office workers",
      "Designers",
      "Engineers",
      "Gamers",
      "VR users",
      "People with accessibility needs",
    ],
    value:
      "Replacing traditional mouse and keyboard interaction with intuitive hand gestures.",
  },
  {
    id: "04",
    name: "Kovert",
    mark: "KOVERT™",
    category: "Tactical Intelligence",
    purpose: "Defence, security, and field operations",
    accent: "Defence",
    tagline: "Mission Ready. Hands Connected.",
    href: null,
    image: null,
    features: [
      "Secure hands-free communications",
      "Silent haptic alerts",
      "Team location & biometric awareness",
      "Drone & robotic system control",
      "AR glasses & night-operation integration",
      "Gesture-based command interface",
    ],
    users: [
      "Armed forces",
      "Law enforcement",
      "Border security",
      "Search and rescue",
      "Disaster response",
      "Security patrols",
    ],
    value:
      "Mission-ready intelligence and control without taking hands off the task.",
  },
  {
    id: "05",
    name: "Kapture",
    mark: "KAPTURE™",
    category: "Recovery & Rehabilitation",
    purpose: "Physiotherapy, rehabilitation, and sports recovery",
    accent: "Recovery",
    tagline: "Recovery. Reinvented.",
    href: null,
    image: null,
    features: [
      "EMS & TENS therapy",
      "Heat & vibration therapy",
      "Grip-strength monitoring",
      "Muscle recovery analytics",
      "Smart Sensor connectivity",
      "AI recovery coaching",
    ],
    users: [
      "Stroke rehabilitation",
      "Hand injury recovery",
      "Arthritis support",
      "Sports therapy",
      "Occupational therapy",
      "Post-surgery rehabilitation",
    ],
    value:
      "Guided recovery built around measurable hand function and progress.",
  },
  {
    id: "06",
    name: "Konnect",
    mark: "KONNECT™",
    category: "Productivity & Workforce",
    purpose: "Manufacturing, warehousing, and logistics",
    accent: "Industry",
    tagline: "Connected Hands. Smarter Work.",
    href: null,
    image: null,
    features: [
      "Digital work instructions & training",
      "Barcode & RFID interaction",
      "Gesture-based controls",
      "Worker safety alerts",
      "Hands-free communication",
      "Productivity & digital twin analytics",
    ],
    users: [
      "Manufacturing plants",
      "Warehouses",
      "Construction sites",
      "Distribution centres",
      "Oil and gas facilities",
      "Industrial maintenance",
    ],
    value: "Fewer errors, safer teams, and better operational visibility.",
  },
];

export const sharedTechnology = [
  "AI & Machine Learning",
  "Gesture Recognition",
  "Haptic Feedback",
  "Bluetooth / Wi-Fi",
  "Edge Computing",
  "Cloud Dashboard",
  "Mobile App Integration",
  "Digital Twin Analytics",
];
